# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b316a87eb9729dbc662864ac28b2a4b0d20888b3af10b527003f8587b79183279df37353d1625fac6c76531ebb834c88f7f776efa0241f8dc280df3f99c2a1ff

test:
  secret_key_base: e38bc8dc141ec0c7b5816058fa5ff665a596ab304ae60781b7315b044b7e535419d3bcd8bd1332d8e3019f7ea6f3a2824c1ad5dbed1e162db5a87a5f85635da5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
